# MediaWiki with MariaDB and a backup

version: '3.2'

networks:
    gmc13bwiki:

services:
    mediawiki:
        build:
            context: .
            dockerfile: ./mediawiki/Dockerfile
            args:
                MYSQL_HOST: ${MYSQL_HOST}
                MYSQL_DATABASE: ${MYSQL_DATABASE}
                MYSQL_USER: ${MYSQL_USER}
                MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        container_name: gmc13bw-media
        restart: always
        ports:
            - 8080:80
        links:
            - database
        volumes:
            - images:/var/www/html/images
            # Reminder: after the container is generated, its LocalSettings.php will only be replaced by generating
            # the container again, so for post installation settings the LocalSettings.php must be positioned in the 
            # mount location, this line below must be uncommented and the container has to be mounted again.
            # - ./LocalSettings.php:/var/www/html/LocalSettings.php
        networks:
            - gmc13bwiki


    database:
        image: mariadb
        container_name: gmc13bw-maria
        restart: always
        ports:
            - 3306:3306
        environment:
            # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        volumes:
            - db:/var/lib/mysql
        networks:
            - gmc13bwiki
        # Force the containter to accept an unprotected root
        # entrypoint: mysqld_safe --skip-grant-tables --user=mysql


    backup:
        build:
            context: .
            dockerfile: ./backup/Dockerfile
            args:
                BACKUP_RETENTION: 14
                MYSQL_HOST: ${MYSQL_HOST}
                MYSQL_USER: ${MYSQL_USER}
                MYSQL_PASSWORD: ${MYSQL_PASSWORD}
                MYSQL_DATABASE: ${MYSQL_DATABASE}
        container_name: gmc13bw-backup
        volumes:
            - images:/images:ro
            - ./backup:/backup
        networks:
           - gmc13bwiki


volumes:
    images:
    db:
