version: '3.1'

# Environment:
#   DB_PASSWORD
#   DB_ROOT_PASSWORD
#   DB_USER
#   DB_NAME

networks:
    mingenet-dev:

services:

    # nginx
    minge-dev-nginx:
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
        container_name: minge-dev-nginx
        restart: always
        ports:
            - "84:80"
        volumes:
            - ./www:/var/www
            - ./nginx:/etc/nginx/conf.d
            - ./nginx_log:/var/log/nginx
        depends_on:
            - minge-dev-php
            - minge-dev-mariadb
            - minge-dev-redis
        networks:
            - mingenet-dev

    # php
    minge-dev-php:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: minge-dev-php
        restart: always
        #ports:
            #- "9000:9000"
        volumes:
            - ./www:/var/www
        networks:
            - mingenet-dev
        environment: 
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}

    # mariadb
    minge-dev-mariadb:
        image: mariadb:10.8
        container_name: minge-dev-mariadb
        ports:
            - "3309:3306"
        volumes:
            - ./mysql:/var/lib/mysql
            #- ./mysql_cnf/my.cnf:/etc/mysql/conf.d/my.cnf
        restart: always
        environment:
            MYSQL_USER: ${DB_USER}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
            interval: 5s
            retries: 5
        networks:
            - mingenet-dev

    # redis
    minge-dev-redis:
        image: redis:7.0
        container_name: minge-dev-redis
        restart: always
        ports:
            - '6380:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass ${DB_PASSWORD}
        volumes: 
            - ./redis:/data
        networks:
            - mingenet-dev

