version: '3.1'

networks:
    mingenet:

services:

    # nginx
    minge-nginx:
        image: nginx:1.22
        container_name: minge-nginx
        restart: always
        ports:
            - "82:80"
        volumes:
            - ./www:/var/www
            - ./nginx:/etc/nginx/conf.d
            - ./nginx_log:/var/log/nginx
        depends_on:
            - minge-php
            - minge-mariadb
            - minge-redis
        networks:
            - mingenet

    # php
    minge-php:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: minge-php
        restart: always
        #ports:
            #- "9000:9000"
        volumes:
            - ./www:/var/www
        networks:
            - mingenet
        environment: 
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}

    # mariadb
    minge-mariadb:
        image: mariadb:10.8
        container_name: minge-mariadb
        ports:
            - "3307:3306"
        volumes:
            - ./mysql:/var/lib/mysql
            - ./mysql_cnf/my.cnf:/etc/mysql/conf.d/my.cnf
        restart: always
        environment:
            MYSQL_USER: ${DB_USER}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
            interval: 5s
            retries: 5
        networks:
            - mingenet

    # redis
    minge-redis:
        image: redis:7.0
        container_name: minge-redis
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass ${DB_PASSWORD}
        volumes: 
            - ./redis:/data
        networks:
            - mingenet

